# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bingo_id', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('genre', models.CharField(max_length=128)),
            ],
        ),
    ]
